### ISSUE TITLE
Failed to post:  {"error":"not found"}

### ISSUE THREAD

**Issue by jsloyer** [schrej/godacov#6]
It looks like this is related to https://github.com/codacy/codacy-coverage-reporter/issues/11

I was trying to upload a coverage file with the following command and got the error `Failed to post:  {"error":"not found"}`. It looks like this is related to https://github.com/codacy/codacy-coverage-reporter/issues/11.

```
godacov -t xxxx -r ./cover.out -c xxx
```

Any ideas?

It looks like this is related to the custom base url, for example the java client supports an environment variable called `CODACY_API_BASE_URL` that allows you to override the base url

**Comment by ryancurrah** [comment]
I had the same problem. Turned out I was using the wrong API token. You need to get the token from `Project -> Settings -> Integrations -> Add Integration -> Project API`.

**Comment by schrej** [comment]
Did that solve your issue?
By now you can also override the baseurl in this tool: https://github.com/schrej/godacov/blob/master/cmd/root.go#L61

**Comment by schrej** [comment]
Closing this for now, if it's still an issue I feel free to reopen it
